name: "Cloudflare DDNS"
version: "1.13.0"
slug: cloudflare-ddns
description: >-
  "An addon based on https://github.com/favonia/cloudflare-ddns to update your public IP on a cloudflare DNS record"
arch:
  - amd64
  - aarch64
  - armv7
  - armhf
url: "https://github.com/favonia/cloudflare-ddns"
image: favonia/cloudflare-ddns
startup: application
boot: auto
options:
  cloudflare_account_id: ""
  cloudflare_api_token: "yourapitokenhere"
  domains: "example.com,my.example.net"
  delete_on_stop: false
  timezone: "Europe/Rome"
  update_interval: "@every 5m"
  update_on_start: true
  proxied: false
  record_comment: "Managed by HA Cloudflare DDNS"
  shoutrrr: ""
environment:
  IP6_PROVIDER: none
  EMOJI: false
