name: Valetudo Proxy
version: "1.0"
panel_icon: "mdi:robot-vacuum"
panel_title: Valetudo
slug: valetudo-proxy
description: Proxy addon for Valetudo
url: "https://github.com/CappyT/hass-utilities"
startup: application
boot: auto
webui: "http://[HOST]:[PORT:5000]/"
watchdog: "http://[HOST]:[PORT:5000]/"
ingress: true
ingress_port: 5000
ingress_entry: /
panel_admin: false
ports:
  5000/tcp: 5000
ports_description:
  5000/tcp: Web interface (Not required for Hass.io Ingress)
host_network: false
devices: []
usb: false
tmpfs: false
full_access: false
environment: {}
options:
  server: "valetudo-yourcustomid.local:80"
schema:
  server: "match(^.+:\\d+$)"
services: []
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map: []
